import type { Verdict } from "./verdict.ts"

export const sectionStart = "<!-- local-verify:start -->"
export const sectionEnd = "<!-- local-verify:end -->"

export interface Provenance {
  readonly sha: string
  readonly agent: string
  readonly at: string
  readonly logs: string
  readonly manifestDigest: string
  readonly tooling: string
  readonly isolation: string
  readonly cache: string
}

const label = { pass: "pass", fail: "FAIL", missing: "MISSING" } as const

const cell = (text: string) => text.replaceAll("|", "\\|").replaceAll("\n", " ")

const rows = (verdict: Verdict) =>
  verdict.checks
    .map((check) => {
      const seconds = check.seconds === undefined ? "-" : `${check.seconds}s`
      const detail =
        check.outcome === "fail" && check.failedStep ? ` (failed at ${cell(check.failedStep)})` : ""
      const where = check.where === undefined ? "-" : check.where
      return `| \`${check.id}\` | ${label[check.outcome]}${detail} | ${where} | ${seconds} | ${cell(check.description)} |`
    })
    .join("\n")

/**
 * The PR body section is rendered only from a verdict, so the checks it lists, their results and
 * the heading line come from the run and never from a person; a failing verdict renders as
 * "Not signed off" so a stale passing section cannot survive a later failing run.
 */
export function renderSection(verdict: Verdict, provenance: Provenance): string {
  const heading = verdict.signedOff
    ? `Signed off by **${cell(provenance.agent)}** at ${provenance.at} for head \`${provenance.sha}\`.`
    : `**Not signed off.** Run by ${cell(provenance.agent)} at ${provenance.at} on head \`${provenance.sha}\`; at least one required check failed or is missing.`
  const logged = verdict.checks.flatMap((check) => (check.logs === undefined ? [] : [check.logs]))
  const dirs = logged.length === 0 ? [provenance.logs] : [...new Set(logged)]
  const statuses = verdict.statuses
    .map((status) => `\`${status.context}\` ${status.state}`)
    .join(", ")
  return [
    sectionStart,
    "## Local verification",
    "",
    heading,
    "",
    "| Check | Result | Ran in | Time | What it covers |",
    "| --- | --- | --- | --- | --- |",
    rows(verdict),
    "",
    `- Head SHA: \`${provenance.sha}\``,
    `- Commit statuses: ${statuses}`,
    `- Log ${dirs.length === 1 ? "directory" : "directories"}: ${dirs.map((dir) => `\`${dir}\``).join(", ")}`,
    `- Manifest: \`tooling/local-verify/manifest.json\` sha256 \`${provenance.manifestDigest.slice(0, 16)}\`; ${provenance.tooling}`,
    `- Isolation: ${provenance.isolation}`,
    `- Turbo cache: ${provenance.cache}`,
    "- Generated by `bun run verify:local --post`; do not edit by hand.",
    sectionEnd,
  ].join("\n")
}

/**
 * Replaces the generated section in place, or appends it when the body has none, and leaves every
 * other part of the body byte-for-byte unchanged.
 */
export function upsertSection(body: string, section: string): string {
  const start = body.indexOf(sectionStart)
  const end = body.indexOf(sectionEnd)
  if (start !== -1 && end > start)
    return `${body.slice(0, start)}${section}${body.slice(end + sectionEnd.length)}`
  const trimmed = body.trimEnd()
  return trimmed === "" ? `${section}\n` : `${trimmed}\n\n${section}\n`
}

export const signoffMarker = (sha: string) => `<!-- local-verify:signoff ${sha} -->`

export function renderSignoff(verdict: Verdict, provenance: Provenance): string {
  return [
    signoffMarker(provenance.sha),
    `Local verification signed off by **${cell(provenance.agent)}** for head \`${provenance.sha}\` at ${provenance.at}.`,
    "",
    ...verdict.checks.map((check) => `- \`${check.id}\`: pass (${check.seconds}s, ${check.where})`),
    "",
    `Statuses set on \`${provenance.sha}\`: ${verdict.statuses.map((status) => `\`${status.context}\``).join(", ")}. Isolation: ${provenance.isolation}. Turbo cache: ${provenance.cache}. Logs: \`${provenance.logs}\`. A later push is not covered and needs a new run.`,
  ].join("\n")
}
