// Generated by @alchemy.run/frontend-frameworks — Node container serve entry.
import * as fs from "node:fs"
import * as http from "node:http"
import * as path from "node:path"
import { fileURLToPath } from "node:url"

const PORT = Number.parseInt(process.env.PORT ?? "3000", 10)
const HOST = process.env.HOST ?? "0.0.0.0"

const CLIENT_DIR = fileURLToPath(new URL("./", import.meta.url))

const MIME = {
  ".html": "text/html; charset=utf-8",
  ".js": "text/javascript; charset=utf-8",
  ".mjs": "text/javascript; charset=utf-8",
  ".cjs": "text/javascript; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".json": "application/json",
  ".svg": "image/svg+xml",
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".gif": "image/gif",
  ".ico": "image/x-icon",
  ".webp": "image/webp",
  ".woff": "font/woff",
  ".woff2": "font/woff2",
  ".txt": "text/plain; charset=utf-8",
  ".xml": "application/xml",
  ".wasm": "application/wasm",
  ".map": "application/json",
}

const existingFile = (filePath, dirIndex = true) => {
  try {
    const st = fs.statSync(filePath)
    if (st.isFile()) return filePath
    // Do not map "/" onto public/index.html — that steals SSR home
    // routes (Nuxt) and serves an unrendered shell. Nested routes
    // like /prerendered still resolve dir/index.html.
    if (dirIndex && st.isDirectory()) {
      const index = path.join(filePath, "index.html")
      try {
        if (fs.statSync(index).isFile()) return index
      } catch {}
    }
  } catch {}
  return undefined
}

const safeJoin = (urlPath) => {
  const relative = urlPath.replace(/^\/+/, "")
  const resolved = path.resolve(CLIENT_DIR, relative)
  const root = path.resolve(CLIENT_DIR)
  if (resolved !== root && !resolved.startsWith(root + path.sep)) {
    return undefined
  }
  return resolved
}

const lookupStatic = (urlPath) => {
  const base = safeJoin(urlPath)
  if (base === undefined) return undefined
  const isRoot = false
  const direct = existingFile(base, !isRoot)
  if (direct) return direct
  return undefined
}

// Never mark files immutable: a service worker, web manifest, or any
// other unhashed file served with `immutable` pins the old app version
// in the browser until the user clears storage, and every deploy must be
// able to bust what it ships.
const sendFile = (res, filePath, status) => {
  const ext = path.extname(filePath).toLowerCase()
  res.writeHead(status, {
    "content-type": MIME[ext] ?? "application/octet-stream",
    "cache-control": "no-cache",
  })
  fs.createReadStream(filePath).pipe(res)
}

const pathnameOf = (url) => {
  try {
    return decodeURIComponent(new URL(url, "http://127.0.0.1").pathname)
  } catch {
    return "/"
  }
}

const server = http.createServer(async (req, res) => {
  try {
    const urlPath = pathnameOf(req.url ?? "/")
    if ((req.method === "GET" || req.method === "HEAD") && urlPath === "/health") {
      res.writeHead(200, { "content-type": "text/plain; charset=utf-8" })
      res.end("ok")
      return
    }

    if (req.method === "GET" || req.method === "HEAD") {
      const file = lookupStatic(urlPath)
      if (file !== undefined) {
        if (req.method === "HEAD") {
          res.writeHead(200)
          res.end()
          return
        }
        sendFile(res, file, 200)
        return
      }
      const spaIndex = lookupStatic("/index.html")
      if (spaIndex !== undefined) {
        if (req.method === "HEAD") {
          res.writeHead(200)
          res.end()
          return
        }
        sendFile(res, spaIndex, 200)
        return
      }
    }

    res.writeHead(404, { "content-type": "text/plain; charset=utf-8" })
    res.end("Not Found")
  } catch (error) {
    if (!res.headersSent) {
      res.writeHead(500, { "content-type": "text/plain; charset=utf-8" })
    }
    res.end(error instanceof Error ? (error.stack ?? error.message) : String(error))
  }
})

server.listen(PORT, HOST)
