import { seededSeries } from "../workspace/series.ts"
import { SettingsPage } from "./model.ts"

/** Fixture settings for the Acme organization and its `storefront` project. Test data. */
export const settings: SettingsPage = SettingsPage.make({
  variables: [
    {
      name: "STRIPE_SECRET_KEY",
      value: "sk_live_••••4f2a",
      secret: true,
      usedBy: "Charge job",
      updated: "3d · dallen",
      environment: "production",
    },
    {
      name: "POSTMARK_TOKEN",
      value: "••••••••91c0",
      secret: true,
      usedBy: "SendEmail job",
      updated: "6d · maya",
      environment: "production",
    },
    {
      name: "OPENAI_API_KEY",
      value: "sk-••••••a7e1",
      secret: true,
      usedBy: "CallModel job",
      updated: "1d · dallen",
      environment: "production",
    },
    {
      name: "LOG_LEVEL",
      value: "info",
      secret: false,
      usedBy: "all runners",
      updated: "6d · dallen",
      environment: "production",
    },
    {
      name: "CART_IDLE_TIMEOUT",
      value: "10m",
      secret: false,
      usedBy: "Cart",
      updated: "1d · dallen",
      environment: "production",
    },
    {
      name: "STRIPE_SECRET_KEY",
      value: "sk_test_••••0b19",
      secret: true,
      usedBy: "Charge job",
      updated: "9d · maya",
      environment: "staging",
    },
    {
      name: "LOG_LEVEL",
      value: "debug",
      secret: false,
      usedBy: "all runners",
      updated: "9d · maya",
      environment: "staging",
    },
    {
      name: "LOG_LEVEL",
      value: "debug",
      secret: false,
      usedBy: "all runners",
      updated: "2d · dallen",
      environment: "development",
    },
  ],
  domains: [
    { host: "storefront.akter.cloud", status: "Default", detail: "Issued automatically" },
    { host: "api.acme.dev", status: "Active", detail: "CNAME verified · certificate renews Dec 2" },
    { host: "ws.acme.dev", status: "Pending DNS", detail: "Add a CNAME to storefront.akter.cloud" },
  ],
  keys: [
    { name: "github-actions", masked: "ak_live_…3f9a", scope: "deploy", lastUsed: "2h ago" },
    {
      name: "support-bot",
      masked: "ak_live_…c021",
      scope: "commands: SupportRoom",
      lastUsed: "now",
    },
    { name: "local-dev", masked: "ak_test_…7e11", scope: "dev environment", lastUsed: "1d ago" },
  ],
  endpoints: [
    { label: "HTTP", value: "https://storefront.akter.cloud" },
    { label: "WebSocket", value: "wss://storefront.akter.cloud/ws" },
    { label: "OpenAPI", value: "https://storefront.akter.cloud/openapi.json" },
    { label: "MCP", value: "https://storefront.akter.cloud/mcp" },
  ],
  integrations: [
    {
      id: "github",
      name: "GitHub",
      detail: "acme/storefront · deploys on push to main",
      connected: true,
    },
    {
      id: "slack",
      name: "Slack",
      detail: "Deploy and dead-letter alerts in a channel",
      connected: false,
    },
    { id: "datadog", name: "Datadog", detail: "Turn metrics and traces", connected: false },
    { id: "opentelemetry", name: "OpenTelemetry", detail: "otlp.acme.dev:4317", connected: true },
    {
      id: "pagerduty",
      name: "PagerDuty",
      detail: "Page on-call when a deploy rolls back",
      connected: false,
    },
  ],
  members: [
    { name: "Dallen Pyrah", email: "dallen@acme.dev", role: "Owner", pending: false },
    { name: "Maya Chen", email: "maya@acme.dev", role: "Admin", pending: false },
    { name: "Sam Okafor", email: "sam@acme.dev", role: "Member", pending: false },
    { name: "Priya Raman", email: "priya@acme.dev", role: "Member", pending: false },
    { name: "Lee Park", email: "lee@acme.dev", role: "Member", pending: true },
  ],
  plan: { name: "Pro", price: "$20 a month plus usage", renews: "November 1" },
  monthToDate: 206.7,
  spendLimit: 500,
  card: { brand: "Visa", last4: "4242", expires: "08 / 28" },
  billingEmail: "billing@acme.dev",
  invoices: [
    { number: "INV-0009", period: "September 2026", amount: 188.4 },
    { number: "INV-0008", period: "August 2026", amount: 151.95 },
    { number: "INV-0007", period: "July 2026", amount: 97.1 },
    { number: "INV-0006", period: "June 2026", amount: 20 },
  ],
  usageMonth: "September",
  meters: [
    { label: "Commands", used: 41_200_000, included: 100_000_000, unit: "count" },
    { label: "Runner hours", used: 1_488, included: 2_000, unit: "hours" },
    { label: "Storage", used: 276, included: 100, unit: "gigabytes" },
    { label: "Egress", used: 88, included: 1_000, unit: "gigabytes" },
  ],
  commandsPerDay: seededSeries({ length: 30, base: 1_380_000, volatility: 260_000, seed: 51 }).map(
    Math.round,
  ),
  projects: [
    {
      project: "storefront",
      commands: "38.0M",
      runnerHours: "1,320",
      storage: "241 GB",
      estimate: 184.2,
    },
    {
      project: "support-bot",
      commands: "3.1M",
      runnerHours: "160",
      storage: "33 GB",
      estimate: 22.1,
    },
    {
      project: "internal-tools",
      commands: "0.1M",
      runnerHours: "8",
      storage: "2 GB",
      estimate: 0.4,
    },
  ],
  audit: [
    {
      key: "e1",
      time: "Oct 2, 14:02",
      person: "Dallen Pyrah",
      action: "deploy.created",
      target: "storefront@a3f9c21",
    },
    {
      key: "e2",
      time: "Oct 2, 11:40",
      person: "Maya Chen",
      action: "variable.updated",
      target: "OPENAI_API_KEY",
    },
    {
      key: "e3",
      time: "Oct 1, 18:12",
      person: "Dallen Pyrah",
      action: "key.created",
      target: "local-dev",
    },
    {
      key: "e4",
      time: "Oct 1, 09:30",
      person: "Maya Chen",
      action: "deploy.rolled_back",
      target: "storefront@5d2e7c3",
    },
    {
      key: "e5",
      time: "Sep 30, 16:05",
      person: "Dallen Pyrah",
      action: "member.invited",
      target: "lee@acme.dev",
    },
    {
      key: "e6",
      time: "Sep 29, 10:44",
      person: "Sam Okafor",
      action: "job.retried",
      target: "Charge · job_2f1",
    },
    {
      key: "e7",
      time: "Sep 28, 08:02",
      person: "Priya Raman",
      action: "domain.added",
      target: "ws.acme.dev",
    },
  ],
  regions: [
    { id: "us-east-1", place: "Virginia", role: "Home" },
    { id: "eu-west-1", place: "Ireland", role: "Replica" },
    { id: "ap-southeast-1", place: "Singapore", role: "Available" },
    { id: "us-west-2", place: "Oregon", role: "Available" },
  ],
})
