import {
  colors,
  dimensions,
  motion,
  radius,
  shadows,
  space,
  typography,
} from "@akter/ui/tokens.stylex"
import * as stylex from "@stylexjs/stylex"

export const install = stylex.create({
  root: {
    display: "inline-flex",
    alignItems: "stretch",
    maxWidth: "100%",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: colors.borderStrong,
    borderRadius: radius.sm,
    backgroundColor: colors.card,
    boxShadow: shadows.md,
    overflow: "hidden",
    fontFamily: typography.mono,
    fontSize: typography.small,
  },
  command: {
    display: "flex",
    alignItems: "center",
    gap: space.md,
    minWidth: 0,
    height: dimensions.controlLg,
    paddingInline: space.lg,
    overflowX: "auto",
    whiteSpace: "nowrap",
    color: colors.foreground,
    scrollbarWidth: "none",
  },
  prompt: { color: colors.subtleForeground, userSelect: "none" },
  copy: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: space.sm,
    flexShrink: 0,
    paddingInline: space.lg,
    borderLeftWidth: 1,
    borderLeftStyle: "solid",
    borderLeftColor: colors.border,
    color: colors.mutedForeground,
    backgroundColor: { default: "transparent", ":hover": colors.accent },
    transitionProperty: "background-color, color",
    transitionDuration: motion.fast,
    outlineWidth: { default: 0, ":focus-visible": 2 },
    outlineStyle: "solid",
    outlineColor: colors.ring,
    outlineOffset: -2,
  },
  done: { display: "none" },
  icon: { width: 15, height: 15 },
})
