import { colors, motion, radius, shadows, space, typography } from "@akter/ui/tokens.stylex"
import * as stylex from "@stylexjs/stylex"
import { queries } from "../styles/breakpoints.stylex.ts"
import { siteColors, siteDimensions } from "../styles/site-tokens.stylex.ts"

export const header = stylex.create({
  root: {
    position: "relative",
    zIndex: 5,
  },
  bordered: {
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: colors.border,
  },
  bar: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    height: siteDimensions.headerHeight,
  },
  home: {
    display: "inline-flex",
    outlineWidth: { default: 0, ":focus-visible": 2 },
    outlineStyle: "solid",
    outlineColor: colors.ring,
    outlineOffset: 4,
    borderRadius: radius.xs,
  },
  spacer: { display: { default: "block", [queries.phoneDown]: "none" } },
  nav: {
    display: { default: "flex", [queries.tabletDown]: "none" },
    alignItems: "center",
    gap: space.xl,
    fontSize: typography.small,
    fontWeight: typography.weightMedium,
  },
  link: {
    color: {
      default: siteColors.bodyForeground,
      ":hover": colors.foreground,
    },
    textDecorationLine: "none",
    textUnderlineOffset: "0.45em",
    textDecorationThickness: 1,
    transitionProperty: "color",
    transitionDuration: motion.fast,
  },
  current: {
    color: colors.foreground,
    fontWeight: typography.weightStrong,
    textDecorationLine: "underline",
  },
  github: {
    display: "inline-flex",
    alignItems: "center",
    gap: space.xs,
    height: "1.875rem",
    paddingInline: space.md,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: colors.borderStrong,
    borderRadius: radius.md,
    backgroundColor: { default: colors.card, ":hover": colors.muted },
    boxShadow: shadows.sm,
    fontFamily: typography.mono,
    fontSize: typography.caption,
    fontWeight: typography.weightRegular,
    color: colors.foreground,
  },
  menu: {
    display: { default: "none", [queries.tabletDown]: "block" },
    position: "relative",
    marginInlineStart: "auto",
  },
  menuButton: {
    display: "inline-flex",
    alignItems: "center",
    gap: space.sm,
    height: "1.875rem",
    paddingInline: space.md,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: colors.borderStrong,
    borderRadius: radius.md,
    backgroundColor: colors.card,
    boxShadow: shadows.sm,
    fontSize: typography.small,
    fontWeight: typography.weightMedium,
    cursor: "pointer",
  },
  menuPanel: {
    position: "absolute",
    right: 0,
    top: "calc(100% + 0.5rem)",
    minWidth: "13rem",
    display: "grid",
    padding: space.sm,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: colors.border,
    borderRadius: radius.md,
    backgroundColor: colors.card,
    boxShadow: shadows.lg,
  },
  menuLink: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    paddingBlock: space.md,
    paddingInline: space.md,
    borderRadius: radius.sm,
    fontSize: typography.body,
    fontWeight: typography.weightMedium,
    backgroundColor: { default: "transparent", ":hover": colors.accent },
  },
  menuCurrent: { backgroundColor: colors.selected },
})
