import { typography } from "@akter/ui/tokens.stylex"
import * as stylex from "@stylexjs/stylex"
import { queries } from "../styles/breakpoints.stylex.ts"
import { siteColors, siteDimensions } from "../styles/site-tokens.stylex.ts"

export const header = stylex.create({
  root: {
    position: "sticky",
    top: 0,
    zIndex: 5,
    backgroundColor: siteColors.page,
  },
  bar: {
    display: "grid",
    gridTemplateColumns: { default: "1fr auto 1fr", [queries.tabletDown]: "1fr auto" },
    alignItems: "center",
    height: siteDimensions.headerHeight,
  },
  home: {
    display: "inline-flex",
    justifySelf: "start",
    outlineWidth: { default: 0, ":focus-visible": 2 },
    outlineStyle: "solid",
    outlineColor: siteColors.ring,
    outlineOffset: 4,
  },
  nav: {
    display: { default: "flex", [queries.tabletDown]: "none" },
    gap: "2rem",
    fontSize: "0.90625rem",
  },
  link: {
    display: "inline-flex",
    alignItems: "center",
    color: { default: siteColors.nav, ":hover": siteColors.ink },
    transitionProperty: "color",
    transitionDuration: "120ms",
  },
  current: { color: siteColors.ink },
  external: { marginInlineStart: "0.3125rem" },
  actions: {
    display: { default: "flex", [queries.tabletDown]: "none" },
    justifyContent: "flex-end",
    gap: "0.625rem",
  },
  github: {
    gap: "0.4375rem",
    fontFamily: typography.sans,
    fontSize: "0.875rem",
    letterSpacing: 0,
    textTransform: "none",
  },
  menu: {
    display: { default: "none", [queries.tabletDown]: "block" },
    position: "relative",
    justifySelf: "end",
  },
  menuButton: {
    display: "inline-flex",
    alignItems: "center",
    gap: "0.5rem",
    height: "2.125rem",
    paddingInline: "0.75rem",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: siteColors.hairline,
    fontFamily: typography.mono,
    fontSize: "0.75rem",
    letterSpacing: "0.05em",
    textTransform: "uppercase",
    cursor: "pointer",
    outlineWidth: { default: 0, ":focus-visible": 2 },
    outlineStyle: "solid",
    outlineColor: siteColors.ring,
    outlineOffset: 3,
  },
  menuPanel: {
    position: "absolute",
    insetInlineEnd: 0,
    top: "calc(100% + 0.5rem)",
    display: "grid",
    minWidth: "14rem",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: siteColors.hairline,
    backgroundColor: siteColors.page,
  },
  menuLink: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    paddingBlock: "0.875rem",
    paddingInline: "1rem",
    fontSize: "1rem",
    borderTopWidth: 1,
    borderTopStyle: "solid",
    borderTopColor: siteColors.hairline,
    backgroundColor: { default: "transparent", ":hover": siteColors.tile },
    ":first-child": { borderTopWidth: 0 },
  },
})
