import { colors, motion, radius, shadows, space, typography } from "@akter/ui/tokens.stylex"
import * as stylex from "@stylexjs/stylex"
import { queries } from "../styles/breakpoints.stylex.ts"
import { siteColors, siteDimensions } from "../styles/site-tokens.stylex.ts"

export const layout = stylex.create({
  grid: {
    display: "grid",
    gridTemplateColumns: {
      default: `${siteDimensions.docsNav} minmax(0, 1fr) ${siteDimensions.docsOutline}`,
      [queries.tabletDown]: `${siteDimensions.docsNav} minmax(0, 1fr)`,
      [queries.phoneDown]: "minmax(0, 1fr)",
    },
    columnGap: { default: "3rem", [queries.tabletDown]: "2.5rem" },
    paddingTop: { default: "2.25rem", [queries.phoneDown]: 0 },
    alignItems: "start",
  },
  article: { minWidth: 0, paddingBottom: space.huge },
})

export const sidebar = stylex.create({
  root: {
    position: "sticky",
    top: "1.25rem",
    maxHeight: "calc(100vh - 2.5rem)",
    overflowY: "auto",
    paddingBottom: space.xl,
    display: { default: "block", [queries.phoneDown]: "none" },
    scrollbarWidth: "thin",
  },
  search: { position: "relative" },
  field: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: space.sm,
    height: "2.25rem",
    paddingInline: space.md,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: { default: colors.borderStrong, ":focus-within": colors.ring },
    borderRadius: radius.sm,
    backgroundColor: colors.card,
    boxShadow: shadows.sm,
  },
  input: {
    flexGrow: 1,
    minWidth: 0,
    height: "100%",
    borderWidth: 0,
    borderStyle: "none",
    outline: "none",
    appearance: "none",
    backgroundColor: "transparent",
    fontFamily: typography.sans,
    fontSize: typography.body,
    color: colors.foreground,
    "::placeholder": { color: colors.mutedForeground },
  },
  kbd: {
    fontFamily: typography.mono,
    fontSize: typography.micro,
    paddingBlock: "0.0625rem",
    paddingInline: space.xs,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: colors.border,
    borderRadius: radius.xs,
    color: colors.mutedForeground,
  },
  results: {
    position: "absolute",
    zIndex: 4,
    insetInline: 0,
    top: "calc(100% + 0.375rem)",
    display: "grid",
    padding: space.xs,
    maxHeight: "22rem",
    overflowY: "auto",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: colors.border,
    borderRadius: radius.md,
    backgroundColor: colors.card,
    boxShadow: shadows.lg,
  },
  result: {
    display: "grid",
    gap: "0.125rem",
    paddingBlock: space.sm,
    paddingInline: space.md,
    borderRadius: radius.sm,
    backgroundColor: {
      default: "transparent",
      ":hover": colors.accent,
      ":focus-visible": colors.accent,
    },
    fontSize: typography.small,
    outline: "none",
  },
  resultTitle: { fontWeight: typography.weightMedium, color: colors.foreground },
  resultText: {
    color: colors.mutedForeground,
    fontSize: typography.caption,
    lineHeight: 1.4,
    display: "-webkit-box",
    WebkitLineClamp: 2,
    WebkitBoxOrient: "vertical",
    overflow: "hidden",
  },
  empty: { padding: space.md, fontSize: typography.small, color: colors.mutedForeground },
  toggle: {
    display: "inline-flex",
    gap: "0.125rem",
    marginTop: space.md,
    padding: "0.1875rem",
    borderRadius: radius.sm,
    backgroundColor: colors.selected,
  },
  mode: {
    paddingBlock: "0.3125rem",
    paddingInline: space.md,
    borderRadius: radius.xs,
    fontFamily: typography.mono,
    fontSize: typography.micro,
    color: colors.mutedForeground,
    cursor: "pointer",
    transitionProperty: "background-color, color",
    transitionDuration: motion.fast,
  },
  modeOn: {
    backgroundColor: colors.card,
    color: colors.foreground,
    boxShadow: shadows.sm,
  },
  group: { marginTop: space.xl, display: "grid" },
  groupTitle: {
    marginBottom: space.sm,
    fontFamily: typography.mono,
    fontSize: typography.micro,
    letterSpacing: typography.trackingMono,
    textTransform: "uppercase",
    color: colors.mutedForeground,
  },
  link: {
    display: "block",
    paddingBlock: "0.375rem",
    paddingInlineStart: "0.875rem",
    borderInlineStartWidth: 1,
    borderInlineStartStyle: "solid",
    borderInlineStartColor: colors.border,
    fontSize: typography.body,
    lineHeight: 1.35,
    color: { default: siteColors.bodyForeground, ":hover": colors.foreground },
  },
  current: {
    paddingInlineStart: "0.8125rem",
    borderInlineStartWidth: 2,
    borderInlineStartColor: colors.foreground,
    fontWeight: typography.weightStrong,
    color: colors.foreground,
  },
})

export const mobile = stylex.create({
  root: {
    display: { default: "none", [queries.phoneDown]: "block" },
    position: "relative",
    marginBottom: space.xl,
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: colors.border,
  },
  summary: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    paddingBlock: space.md,
    fontFamily: typography.mono,
    fontSize: typography.caption,
    textTransform: "uppercase",
    letterSpacing: typography.trackingMono,
    cursor: "pointer",
  },
  panel: { paddingBottom: space.xl },
})

export const article = stylex.create({
  crumb: {
    fontFamily: typography.mono,
    fontSize: typography.micro,
    letterSpacing: typography.trackingMono,
    textTransform: "uppercase",
    color: colors.mutedForeground,
    display: { default: "block", [queries.phoneDown]: "none" },
  },
  title: {
    marginTop: space.md,
    fontFamily: typography.display,
    fontWeight: 400,
    fontSize: { default: "3.375rem", [queries.phoneDown]: "2.5rem" },
    letterSpacing: "-0.03em",
    lineHeight: 1,
    color: colors.foreground,
    overflowWrap: "anywhere",
  },
  lead: {
    marginTop: space.lg,
    maxWidth: "40rem",
    fontSize: { default: "1.0625rem", [queries.phoneDown]: typography.lead },
    lineHeight: 1.6,
    color: siteColors.bodyForeground,
    textWrap: "pretty",
  },
  leadLink: {
    textDecorationLine: "underline",
    textDecorationColor: colors.borderStrong,
    textUnderlineOffset: "0.2em",
  },
  content: { marginTop: space.xl },
  next: {
    display: "grid",
    gridTemplateColumns: {
      default: "repeat(2, minmax(0, 1fr))",
      [queries.phoneDown]: "minmax(0, 1fr)",
    },
    gap: space.lg,
    marginTop: "3.5rem",
  },
  card: {
    display: "grid",
    gap: space.xs,
    padding: space.xl,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: { default: colors.border, ":hover": colors.borderStrong },
    borderRadius: radius.md,
    backgroundColor: colors.card,
    boxShadow: shadows.md,
    transitionProperty: "border-color",
    transitionDuration: motion.fast,
  },
  cardLabel: {
    fontFamily: typography.mono,
    fontSize: typography.micro,
    letterSpacing: typography.trackingMono,
    textTransform: "uppercase",
    color: colors.mutedForeground,
  },
  cardTitle: {
    fontFamily: typography.display,
    fontSize: "1.5rem",
    letterSpacing: "-0.02em",
    lineHeight: 1.15,
    color: colors.foreground,
  },
  agent: { display: "grid", gap: space.lg },
  agentBar: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    justifyContent: "space-between",
    gap: space.md,
  },
  agentNote: {
    maxWidth: "36rem",
    fontSize: typography.small,
    lineHeight: 1.55,
    color: colors.mutedForeground,
  },
  agentActions: { display: "flex", gap: space.sm, flexWrap: "wrap" },
  agentPre: {
    margin: 0,
    padding: space.xl,
    overflowX: "auto",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: colors.border,
    borderRadius: radius.md,
    backgroundColor: colors.code,
    fontFamily: typography.mono,
    fontSize: "0.78125rem",
    lineHeight: 1.7,
    whiteSpace: "pre-wrap",
    overflowWrap: "anywhere",
    color: siteColors.bodyForeground,
  },
})

export const outline = stylex.create({
  root: {
    position: "sticky",
    top: "1.25rem",
    display: { default: "block", [queries.tabletDown]: "none" },
    fontSize: "0.84375rem",
  },
  title: {
    fontFamily: typography.mono,
    fontSize: typography.micro,
    letterSpacing: typography.trackingMono,
    textTransform: "uppercase",
    color: colors.mutedForeground,
  },
  list: { display: "grid", marginTop: space.md },
  link: {
    display: "block",
    paddingBlock: "0.3125rem",
    lineHeight: 1.4,
    color: { default: colors.mutedForeground, ":hover": colors.foreground },
  },
  nested: { paddingInlineStart: space.md },
  current: { color: colors.foreground, fontWeight: typography.weightStrong },
  agent: {
    marginTop: space.xxl,
    padding: space.lg,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: colors.border,
    borderRadius: radius.md,
    backgroundColor: colors.card,
    boxShadow: shadows.md,
  },
  agentLink: {
    display: "block",
    width: "100%",
    paddingBlock: "0.25rem",
    textAlign: "start",
    fontFamily: typography.mono,
    fontSize: typography.caption,
    color: { default: colors.foreground, ":hover": colors.mutedForeground },
    cursor: "pointer",
  },
  agentList: { display: "grid", marginTop: space.sm },
})
