import { colors, motion, radius, shadows, space, typography } from "@akter/ui/tokens.stylex"
import * as stylex from "@stylexjs/stylex"
import { queries } from "../styles/breakpoints.stylex.ts"
import { siteColors } from "../styles/site-tokens.stylex.ts"

export const prose = stylex.create({
  paragraph: {
    marginTop: space.lg,
    fontSize: { default: "0.96875rem", [queries.phoneDown]: "0.9375rem" },
    lineHeight: 1.7,
    color: siteColors.bodyForeground,
    maxWidth: "46rem",
  },
  h2: {
    position: "relative",
    display: "flex",
    alignItems: "center",
    gap: space.md,
    marginTop: { default: "3.5rem", [queries.phoneDown]: "2.75rem" },
    fontFamily: typography.display,
    fontWeight: 400,
    fontSize: { default: "1.875rem", [queries.phoneDown]: "1.5rem" },
    letterSpacing: "-0.02em",
    lineHeight: 1.15,
    color: colors.foreground,
    scrollMarginTop: "5rem",
  },
  h3: {
    position: "relative",
    marginTop: "2.25rem",
    fontFamily: typography.sans,
    fontWeight: typography.weightStrong,
    fontSize: "1.125rem",
    letterSpacing: "-0.01em",
    lineHeight: 1.3,
    color: colors.foreground,
    scrollMarginTop: "5rem",
  },
  h4: {
    position: "relative",
    marginTop: "1.75rem",
    fontFamily: typography.sans,
    fontWeight: typography.weightStrong,
    fontSize: "0.96875rem",
    color: colors.foreground,
    scrollMarginTop: "5rem",
  },
  step: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    width: "2rem",
    height: "2rem",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: colors.border,
    borderRadius: radius.sm,
    backgroundColor: colors.card,
    boxShadow: shadows.sm,
    fontFamily: typography.mono,
    fontSize: typography.caption,
    letterSpacing: 0,
    color: colors.foreground,
  },
  anchor: {
    position: "absolute",
    insetInlineStart: "-1.25rem",
    opacity: { default: 0, ":focus-visible": 1 },
    fontFamily: typography.mono,
    fontSize: typography.small,
    color: colors.subtleForeground,
    textDecorationLine: "none",
  },
  list: {
    marginTop: space.md,
    paddingInlineStart: "1.25rem",
    maxWidth: "46rem",
    fontSize: "0.96875rem",
    lineHeight: 1.65,
    color: siteColors.bodyForeground,
    display: "grid",
    gap: space.sm,
  },
  bullets: { listStyleType: "disc" },
  numbers: { listStyleType: "decimal" },
  item: { paddingInlineStart: space.xs, "::marker": { color: colors.subtleForeground } },
  link: {
    color: colors.foreground,
    textDecorationLine: "underline",
    textDecorationColor: { default: colors.borderStrong, ":hover": colors.foreground },
    textUnderlineOffset: "0.2em",
    transitionProperty: "text-decoration-color",
    transitionDuration: motion.fast,
  },
  code: {
    fontFamily: typography.mono,
    fontSize: "0.8125em",
    paddingBlock: "0.08em",
    paddingInline: "0.34em",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: colors.border,
    borderRadius: radius.xs,
    backgroundColor: colors.card,
    color: colors.foreground,
    overflowWrap: "anywhere",
  },
  strong: { fontWeight: typography.weightStrong, color: colors.foreground },
  quote: {
    marginTop: space.xl,
    paddingBlock: space.md,
    paddingInline: space.lg,
    borderRadius: radius.md,
    backgroundColor: colors.highlight,
    color: siteColors.bodyForeground,
    fontSize: "0.9375rem",
    lineHeight: 1.65,
    maxWidth: "46rem",
  },
  rule: {
    marginBlock: "2.5rem",
    borderWidth: 0,
    borderTopWidth: 1,
    borderTopStyle: "solid",
    borderTopColor: colors.border,
  },
  tableWrap: {
    marginTop: space.xl,
    overflowX: "auto",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: colors.border,
    borderRadius: radius.md,
    backgroundColor: colors.card,
    boxShadow: shadows.sm,
  },
  table: {
    width: "100%",
    minWidth: "32rem",
    borderCollapse: "collapse",
    fontSize: "0.84375rem",
    lineHeight: 1.5,
    textAlign: "start",
  },
  th: {
    paddingBlock: space.md,
    paddingInline: space.lg,
    textAlign: "start",
    verticalAlign: "bottom",
    fontWeight: typography.weightStrong,
    fontSize: typography.caption,
    color: colors.mutedForeground,
    backgroundColor: colors.background,
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: colors.border,
  },
  td: {
    paddingBlock: space.md,
    paddingInline: space.lg,
    verticalAlign: "top",
    color: siteColors.bodyForeground,
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: colors.border,
    minWidth: "7rem",
  },
  figure: {
    position: "relative",
    marginTop: space.lg,
    marginInline: 0,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: colors.border,
    borderRadius: radius.md,
    backgroundColor: colors.card,
    boxShadow: shadows.md,
    overflow: "hidden",
  },
  caption: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: space.lg,
    paddingBlock: space.md,
    paddingInline: space.lg,
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: colors.border,
    fontFamily: typography.mono,
    fontSize: typography.caption,
    color: colors.mutedForeground,
  },
  pre: {
    margin: 0,
    paddingBlock: space.lg,
    paddingInline: { default: space.xl, [queries.phoneDown]: space.lg },
    overflowX: "auto",
    backgroundColor: colors.code,
    fontFamily: typography.mono,
    fontSize: { default: "0.78125rem", [queries.phoneDown]: "0.71875rem" },
    lineHeight: 1.75,
    tabSize: 2,
    color: siteColors.bodyForeground,
  },
  codeBlock: { fontFamily: "inherit", display: "block", whiteSpace: "pre" },
  copy: {
    position: "absolute",
    insetBlockStart: space.sm,
    insetInlineEnd: space.sm,
    height: "1.5rem",
    paddingInline: space.sm,
    borderRadius: radius.xs,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: colors.border,
    backgroundColor: colors.card,
    fontFamily: typography.sans,
    fontSize: typography.micro,
    color: colors.mutedForeground,
    opacity: {
      default: 0,
      ":focus-visible": 1,
      [stylex.when.ancestor(":hover")]: 1,
      "@media (hover: none)": 1,
    },
    cursor: "pointer",
    transitionProperty: "opacity",
    transitionDuration: motion.fast,
  },
})
