import { colors, motion, radius, shadows, space, typography } from "@akter/ui/tokens.stylex"
import * as stylex from "@stylexjs/stylex"
import { queries } from "../styles/breakpoints.stylex.ts"
import { siteColors } from "../styles/site-tokens.stylex.ts"

export const period = stylex.create({
  root: {
    display: "inline-flex",
    gap: "0.125rem",
    marginTop: space.xl,
    padding: "0.1875rem",
    borderRadius: radius.sm,
    backgroundColor: colors.selected,
  },
  option: {
    paddingBlock: "0.375rem",
    paddingInline: space.lg,
    borderRadius: radius.xs,
    fontSize: typography.small,
    color: colors.mutedForeground,
    cursor: "pointer",
  },
  on: { backgroundColor: colors.card, color: colors.foreground, boxShadow: shadows.sm },
})

export const tiers = stylex.create({
  grid: {
    display: "grid",
    gridTemplateColumns: {
      default: "repeat(4, minmax(0, 1fr))",
      [queries.desktopDown]: "repeat(2, minmax(0, 1fr))",
      [queries.phoneDown]: "minmax(0, 1fr)",
    },
    gap: space.lg,
    alignItems: "stretch",
  },
  card: { display: "flex", flexDirection: "column", minWidth: 0 },
  art: {
    display: "flex",
    alignItems: "flex-end",
    justifyContent: "center",
    height: "7.5rem",
    paddingBottom: space.md,
    backgroundColor: colors.background,
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: colors.border,
  },
  svg: { width: "86%", height: "auto", overflow: "visible", opacity: 0.94 },
  inverted: { filter: "invert(1)" },
  body: {
    display: "flex",
    flexDirection: "column",
    flexGrow: 1,
    padding: `${space.xl} ${space.xl} ${space.xl}`,
  },
  name: { fontSize: "1.75rem" },
  price: {
    display: "flex",
    alignItems: "baseline",
    gap: space.sm,
    marginTop: space.md,
    fontFamily: typography.display,
    fontSize: "3.25rem",
    letterSpacing: "-0.03em",
    lineHeight: 1,
    fontVariantNumeric: "lining-nums",
  },
  custom: { fontSize: "2.75rem" },
  per: {
    fontFamily: typography.sans,
    fontSize: typography.small,
    letterSpacing: 0,
    color: colors.mutedForeground,
  },
  perInverse: { color: siteColors.inverseMuted },
  summary: {
    marginTop: space.sm,
    minHeight: "2.75rem",
    fontSize: typography.body,
    lineHeight: 1.5,
    color: siteColors.bodyForeground,
  },
  summaryInverse: { color: siteColors.inverseSoft },
  features: {
    display: "grid",
    flexGrow: 1,
    alignContent: "start",
    margin: `${space.lg} 0 ${space.xl}`,
    borderTopWidth: 1,
    borderTopStyle: "solid",
    borderTopColor: colors.border,
  },
  featuresInverse: { borderTopColor: siteColors.inverseHairline },
  feature: {
    display: "grid",
    gridTemplateColumns: "1.125rem 1fr",
    paddingBlock: "0.5rem",
    fontSize: typography.body,
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: colors.border,
    color: siteColors.bodyForeground,
    "::before": {
      content: '"■"',
      fontSize: "0.4375rem",
      paddingTop: "0.3125rem",
      color: colors.mutedForeground,
    },
  },
  featureInverse: {
    borderBottomColor: siteColors.inverseHairline,
    color: siteColors.inverseSoft,
    "::before": { color: siteColors.inverseMuted },
  },
})

export const estimator = stylex.create({
  root: {
    display: "grid",
    gridTemplateColumns: { default: "1.1fr 1fr", [queries.tabletDown]: "minmax(0, 1fr)" },
    marginTop: space.xl,
  },
  controls: {
    padding: { default: space.xxl, [queries.phoneDown]: space.xl },
    display: "grid",
    gap: space.lg,
  },
  group: { margin: 0, padding: 0, borderWidth: 0, borderStyle: "none", minWidth: 0 },
  legend: {
    padding: 0,
    marginBottom: space.sm,
    fontSize: typography.small,
    fontWeight: typography.weightStrong,
    color: colors.foreground,
  },
  segments: {
    display: "grid",
    gridTemplateColumns: "repeat(4, minmax(0, 1fr))",
    gap: "0.125rem",
    padding: "0.1875rem",
    borderRadius: radius.sm,
    backgroundColor: colors.selected,
  },
  option: { position: "relative", display: "block" },
  radio: {
    position: "absolute",
    inset: 0,
    width: "100%",
    height: "100%",
    margin: 0,
    opacity: 0,
    cursor: "pointer",
  },
  label: {
    display: "block",
    paddingBlock: "0.4375rem",
    textAlign: "center",
    borderRadius: radius.xs,
    fontFamily: typography.mono,
    fontSize: typography.caption,
    color: {
      default: colors.mutedForeground,
      [stylex.when.siblingBefore(":checked")]: colors.foreground,
    },
    backgroundColor: {
      default: "transparent",
      [stylex.when.siblingBefore(":checked")]: colors.card,
    },
    boxShadow: {
      default: "none",
      [stylex.when.siblingBefore(":checked")]: shadows.sm,
      [stylex.when.siblingBefore(":focus-visible")]: `0 0 0 2px ${colors.ring}`,
    },
    transitionProperty: "background-color, color",
    transitionDuration: motion.fast,
  },
  note: { fontSize: typography.caption, lineHeight: 1.55, color: colors.mutedForeground },
  bill: {
    padding: { default: space.xxl, [queries.phoneDown]: space.xl },
    borderInlineStartWidth: { default: 1, [queries.tabletDown]: 0 },
    borderInlineStartStyle: "solid",
    borderInlineStartColor: colors.border,
    borderTopWidth: { default: 0, [queries.tabletDown]: 1 },
    borderTopStyle: "solid",
    borderTopColor: colors.border,
    fontFamily: typography.mono,
    fontSize: typography.small,
  },
  head: {
    display: "flex",
    justifyContent: "space-between",
    paddingBottom: space.md,
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: colors.border,
    fontSize: typography.caption,
    color: colors.mutedForeground,
  },
  line: {
    display: "grid",
    gridTemplateColumns: "1fr auto",
    gap: space.lg,
    paddingBlock: "0.5625rem",
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: colors.border,
    color: colors.foreground,
  },
  detail: {
    display: "block",
    marginTop: "0.125rem",
    fontSize: typography.caption,
    color: colors.mutedForeground,
  },
  amount: { fontVariantNumeric: "tabular-nums", whiteSpace: "nowrap" },
  split: {
    display: "flex",
    height: "0.5rem",
    marginTop: space.lg,
    gap: "0.125rem",
    borderRadius: radius.full,
    overflow: "hidden",
    backgroundColor: colors.chartGrid,
  },
  segment: {
    minWidth: 0,
    backgroundColor: colors.foreground,
    transitionProperty: "width",
    transitionDuration: motion.slow,
    transitionTimingFunction: motion.easeOut,
  },
  total: {
    display: "flex",
    alignItems: "baseline",
    justifyContent: "space-between",
    gap: space.lg,
    paddingTop: space.lg,
  },
  totalValue: {
    fontFamily: typography.display,
    fontWeight: 400,
    fontSize: { default: "3rem", [queries.phoneDown]: "2.5rem" },
    letterSpacing: "-0.02em",
    lineHeight: 1,
    fontVariantNumeric: "lining-nums",
    color: colors.foreground,
  },
  stamp: {
    display: "inline-block",
    marginTop: space.md,
    paddingBlock: "0.25rem",
    paddingInline: space.md,
    borderRadius: radius.xs,
    backgroundColor: colors.primary,
    color: colors.primaryForeground,
    fontSize: typography.micro,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
  },
})

export const compare = stylex.create({
  wrap: { overflowX: "auto", padding: `${space.sm} ${space.lg} ${space.xl}` },
  table: { width: "100%", minWidth: "40rem", fontSize: typography.body },
  corner: { width: "34%" },
  head: {
    paddingBlock: space.md,
    paddingInline: space.lg,
    textAlign: "center",
    fontFamily: typography.mono,
    fontSize: typography.micro,
    fontWeight: typography.weightRegular,
    letterSpacing: typography.trackingMono,
    textTransform: "uppercase",
    color: colors.mutedForeground,
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: colors.border,
  },
  group: {
    paddingTop: space.xl,
    paddingBottom: space.sm,
    paddingInline: space.lg,
    fontFamily: typography.mono,
    fontSize: typography.micro,
    letterSpacing: typography.trackingMono,
    textTransform: "uppercase",
    textAlign: "start",
    fontWeight: typography.weightRegular,
    color: colors.mutedForeground,
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: colors.border,
  },
  label: {
    position: "sticky",
    insetInlineStart: 0,
    zIndex: 1,
    backgroundColor: colors.card,
    paddingBlock: "0.6875rem",
    paddingInline: space.lg,
    textAlign: "start",
    fontWeight: typography.weightRegular,
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: colors.border,
  },
  cell: {
    paddingBlock: "0.6875rem",
    paddingInline: space.lg,
    textAlign: "center",
    color: siteColors.bodyForeground,
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: colors.border,
  },
  yes: { fontSize: "0.5rem", color: colors.foreground },
  no: { color: colors.subtleForeground },
  featured: { backgroundColor: colors.accent },
})

/**
 * Attributes for the estimator's radio inputs. The default marker lets each label style itself
 * from its radio's checked state, so the choice reads without a script. It is composed here
 * because markers must be created in a module the StyleX compiler processes.
 */
export const radioAttributes = stylex.attrs(estimator.radio, stylex.defaultMarker())
