import * as stylex from "@stylexjs/stylex"
import { revealMarker } from "../markers.stylex.ts"
import {
  borders,
  colors,
  conditions,
  layers,
  motion,
  radius,
  shadows,
  space,
  typography,
} from "../tokens.stylex.ts"

const draw = stylex.keyframes({
  from: { clipPath: "inset(0 100% 0 0)" },
  to: { clipPath: "inset(0 0 0 0)" },
})

const grow = stylex.keyframes({
  from: { transform: "scaleY(0)" },
  to: { transform: "scaleY(1)" },
})

/** Shared chart chrome: plot frames, axis labels, hover readouts and their reveal on hover. */
export const chartStyles = stylex.create({
  figure: { display: "grid", gap: space.sm, minWidth: 0, margin: 0, color: colors.chartLine },
  plot: { position: "relative", minWidth: 0 },
  svg: { position: "absolute", inset: 0, width: "100%", height: "100%", overflow: "visible" },
  drawIn: {
    animationName: { default: draw, [conditions.reducedMotion]: "none" },
    animationDuration: motion.draw,
    animationTimingFunction: motion.easeOut,
    animationFillMode: "both",
  },
  growIn: {
    transformOrigin: "bottom",
    animationName: { default: grow, [conditions.reducedMotion]: "none" },
    animationDuration: motion.slow,
    animationTimingFunction: motion.easeOut,
    animationFillMode: "both",
  },
  grid: { stroke: colors.chartGrid, strokeWidth: 1, vectorEffect: "non-scaling-stroke" },
  baseline: { stroke: colors.chartMuted, strokeWidth: 1, vectorEffect: "non-scaling-stroke" },
  marker: {
    stroke: colors.chartSecondary,
    strokeWidth: 1,
    strokeDasharray: "2 3",
    vectorEffect: "non-scaling-stroke",
  },
  linePrimary: {
    fill: "none",
    stroke: colors.chartLine,
    strokeWidth: 1.5,
    strokeLinejoin: "round",
    strokeLinecap: "round",
    vectorEffect: "non-scaling-stroke",
  },
  lineSecondary: {
    fill: "none",
    stroke: colors.chartSecondary,
    strokeWidth: 1.25,
    strokeDasharray: "4 3",
    strokeLinejoin: "round",
    vectorEffect: "non-scaling-stroke",
  },
  lineMuted: {
    fill: "none",
    stroke: colors.chartMuted,
    strokeWidth: 1.25,
    strokeLinejoin: "round",
    vectorEffect: "non-scaling-stroke",
  },
  axisY: {
    position: "absolute",
    insetInlineEnd: `calc(100% + ${space.sm})`,
    translate: "0 -50%",
    color: colors.subtleForeground,
    fontSize: typography.micro,
    fontVariantNumeric: "tabular-nums",
    whiteSpace: "nowrap",
    lineHeight: 1,
  },
  axisX: {
    position: "relative",
    height: "1rem",
    color: colors.subtleForeground,
    fontSize: typography.micro,
    fontVariantNumeric: "tabular-nums",
  },
  tickX: { position: "absolute", insetBlockStart: 0, whiteSpace: "nowrap", translate: "-50% 0" },
  tickFirst: { translate: "0 0" },
  tickLast: { translate: "-100% 0" },
  hoverLayer: { position: "absolute", inset: 0 },
  column: { position: "absolute", insetBlock: 0, cursor: "crosshair" },
  crosshair: {
    position: "absolute",
    insetBlock: 0,
    insetInlineStart: "50%",
    width: "1px",
    backgroundColor: colors.borderStrong,
    opacity: { default: 0, [stylex.when.ancestor(":hover", revealMarker)]: 1 },
  },
  dot: {
    position: "absolute",
    insetInlineStart: "50%",
    width: "0.4375rem",
    height: "0.4375rem",
    translate: "-50% -50%",
    borderRadius: radius.full,
    borderWidth: borders.strong,
    borderStyle: "solid",
    borderColor: colors.chartLine,
    backgroundColor: colors.card,
    opacity: { default: 0, [stylex.when.ancestor(":hover", revealMarker)]: 1 },
  },
  dotSecondary: { borderColor: colors.chartSecondary },
  readout: {
    position: "absolute",
    insetBlockStart: 0,
    zIndex: layers.tooltip,
    display: "grid",
    gap: space.xs,
    minWidth: "8.5rem",
    paddingBlock: space.sm,
    paddingInline: "0.625rem",
    borderWidth: borders.hairline,
    borderStyle: "solid",
    borderColor: colors.border,
    borderRadius: radius.sm,
    backgroundColor: colors.popover,
    color: colors.foreground,
    boxShadow: shadows.popover,
    fontSize: typography.caption,
    pointerEvents: "none",
    opacity: { default: 0, [stylex.when.ancestor(":hover", revealMarker)]: 1 },
    visibility: { default: "hidden", [stylex.when.ancestor(":hover", revealMarker)]: "visible" },
  },
  readoutRight: { insetInlineStart: `calc(50% + ${space.md})` },
  readoutLeft: { insetInlineEnd: `calc(50% + ${space.md})` },
  readoutTitle: { color: colors.mutedForeground, whiteSpace: "nowrap" },
  readoutRow: {
    display: "grid",
    gridTemplateColumns: "auto 1fr auto",
    alignItems: "center",
    gap: space.s,
    whiteSpace: "nowrap",
  },
  readoutValue: { fontVariantNumeric: "tabular-nums", fontWeight: typography.weightMedium },
  swatch: {
    width: "0.75rem",
    height: 0,
    borderBlockStartWidth: borders.strong,
    borderBlockStartStyle: "solid",
  },
  swatchPrimary: { borderBlockStartColor: colors.chartLine },
  swatchSecondary: {
    borderBlockStartColor: colors.chartSecondary,
    borderBlockStartStyle: "dashed",
  },
  swatchMuted: { borderBlockStartColor: colors.chartMuted },
  legend: {
    display: "flex",
    gap: space.lg,
    flexWrap: "wrap",
    color: colors.mutedForeground,
    fontSize: typography.caption,
  },
  legendItem: { display: "inline-flex", alignItems: "center", gap: space.s },
  summary: {
    position: "absolute",
    width: "1px",
    height: "1px",
    overflow: "hidden",
    clipPath: "inset(50%)",
    whiteSpace: "nowrap",
  },
})

/** Data-derived positions for chart parts, as CSS percentages or lengths. */
export const placement = stylex.create({
  left: (value: string) => ({ insetInlineStart: value }),
  top: (value: string) => ({ insetBlockStart: value }),
  width: (value: string) => ({ width: value }),
  height: (value: string) => ({ height: value }),
  span: (left: string, width: string) => ({ insetInlineStart: left, width }),
  gutter: (value: string) => ({ marginInlineStart: value }),
  delay: (value: string) => ({ animationDelay: value }),
})

/** A fraction as a CSS percentage with enough precision for sub-pixel placement. */
export const percent = (fraction: number): string => `${(fraction * 100).toFixed(3)}%`
