import { colors, conditions, space, typography } from "@akter/ui/tokens.stylex"
import * as stylex from "@stylexjs/stylex"

const hairline = "light-dark(rgb(55 48 31 / 0.13), rgb(236 235 231 / 0.12))"
const muted = "light-dark(rgb(11 13 11 / 0.55), rgb(236 235 231 / 0.55))"
const tileColor = "light-dark(#f1f0ed, #1b1c1a)"

/**
 * The signed-out frame: a logo-only top bar, one 380px column, and the strip of containers along
 * the bottom of the viewport. Every edge is square.
 */
export const frameStyles = stylex.create({
  page: {
    display: "grid",
    gridTemplateRows: "auto 1fr auto",
    minHeight: "100dvh",
    backgroundColor: colors.frame,
    color: colors.foreground,
  },
  bar: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: space.lg,
    boxSizing: "border-box",
    width: "100%",
    maxWidth: "70.5rem",
    height: "4.25rem",
    marginInline: "auto",
    paddingInline: space.xl,
  },
  logo: {
    display: "inline-flex",
    alignItems: "center",
    gap: "0.5625rem",
    fontSize: "1.1875rem",
    fontWeight: 600,
    letterSpacing: "-0.025em",
    color: colors.foreground,
  },
  alt: { fontSize: "0.875rem", color: muted, textAlign: "end" },
  altLink: {
    marginInlineStart: space.xxs,
    color: colors.foreground,
    fontWeight: 500,
    textDecorationLine: { default: "none", ":hover": "underline" },
    textUnderlineOffset: "3px",
  },
  column: {
    boxSizing: "border-box",
    width: "100%",
    maxWidth: "calc(23.75rem + 3rem)",
    marginInline: "auto",
    paddingInline: space.xl,
    paddingBlockStart: { default: "4.5rem", [conditions.compact]: space.xxl },
    paddingBlockEnd: { default: space.huge, [conditions.compact]: "2.5rem" },
  },
  wide: { maxWidth: "calc(32rem + 3rem)" },
  strip: { overflow: "hidden", paddingBlockEnd: "1.75rem" },
  stripArt: {
    overflow: "hidden",
    position: "relative",
    insetInlineStart: "50%",
    width: "max(min(100% - 3rem, 67.5rem), 45rem)",
    transform: "translateX(-50%)",
  },
})

/** Headings, text, form controls and buttons shared by every signed-out screen. */
export const authStyles = stylex.create({
  title: {
    fontSize: typography.displaySm,
    fontWeight: 450,
    letterSpacing: "-0.03em",
    lineHeight: 1.04,
    color: colors.foreground,
  },
  lead: {
    marginBlockStart: "0.625rem",
    fontSize: "0.96875rem",
    lineHeight: 1.5,
    color: colors.mutedForeground,
  },
  strong: { color: colors.foreground, fontWeight: 500 },
  tile: {
    display: "grid",
    placeItems: "center",
    width: "3.5rem",
    height: "3.5rem",
    marginBlockEnd: "1.625rem",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: colors.foreground,
    backgroundColor: tileColor,
    color: colors.foreground,
    fontFamily: typography.mono,
    fontSize: "1.25rem",
    textTransform: "uppercase",
  },
  oauth: { display: "grid", gap: "0.625rem", marginBlockStart: "1.875rem" },
  provider: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "0.625rem",
    height: "2.75rem",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: { default: hairline, ":hover:not(:disabled)": colors.ring },
    borderRadius: 0,
    backgroundColor: colors.card,
    color: colors.foreground,
    fontFamily: "inherit",
    fontSize: "0.90625rem",
    fontWeight: 500,
    cursor: { default: "pointer", ":disabled": "default" },
    opacity: { default: 1, ":disabled": 0.45 },
  },
  divider: {
    display: "flex",
    alignItems: "center",
    gap: space.md,
    marginBlockStart: "1.375rem",
    marginBlockEnd: space.s,
    color: muted,
    fontFamily: typography.mono,
    fontSize: typography.micro,
    letterSpacing: "0.07em",
    textTransform: "uppercase",
    "::before": {
      content: "''",
      flex: "1",
      borderBlockStartWidth: "1px",
      borderBlockStartStyle: "solid",
      borderBlockStartColor: hairline,
    },
    "::after": {
      content: "''",
      flex: "1",
      borderBlockStartWidth: "1px",
      borderBlockStartStyle: "solid",
      borderBlockStartColor: hairline,
    },
  },
  form: { display: "grid", gap: space.lg, marginBlockStart: space.lg },
  field: { display: "grid", gap: "0.4375rem", minWidth: 0 },
  fieldHead: {
    display: "flex",
    alignItems: "baseline",
    justifyContent: "space-between",
    gap: space.md,
  },
  label: { fontSize: "0.84375rem", fontWeight: 500, lineHeight: 1.2, color: colors.foreground },
  input: {
    boxSizing: "border-box",
    width: "100%",
    minWidth: 0,
    height: "2.625rem",
    paddingInline: space.md,
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: {
      default: hairline,
      ":hover": colors.ring,
      ":focus": colors.foreground,
      ":is([aria-invalid='true'])": colors.destructive,
    },
    borderRadius: 0,
    backgroundColor: colors.card,
    color: colors.foreground,
    fontFamily: "inherit",
    fontSize: "0.9375rem",
    outlineStyle: "solid",
    outlineWidth: { default: 0, ":focus-visible": "1px" },
    outlineColor: colors.foreground,
    outlineOffset: 0,
    "::placeholder": { color: colors.subtleForeground },
  },
  mono: { fontFamily: typography.mono, fontSize: "0.9375rem", letterSpacing: "0.08em" },
  hint: { fontSize: "0.78125rem", lineHeight: 1.5, color: muted },
  link: {
    fontSize: "0.8125rem",
    color: { default: muted, ":hover": colors.foreground },
    textDecorationLine: { default: "none", ":hover": "underline" },
    textUnderlineOffset: "3px",
  },
  error: { fontSize: "0.8125rem", lineHeight: 1.45, color: colors.destructive },
  button: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    boxSizing: "border-box",
    width: "100%",
    height: "2.75rem",
    paddingInline: space.lg,
    borderWidth: "1px",
    borderStyle: "solid",
    borderRadius: 0,
    fontFamily: typography.mono,
    fontSize: "0.78125rem",
    letterSpacing: "0.05em",
    lineHeight: 1,
    textTransform: "uppercase",
    whiteSpace: "nowrap",
    cursor: { default: "pointer", ":disabled": "default" },
    opacity: { default: 1, ":disabled": 0.45 },
  },
  primary: {
    backgroundColor: { default: colors.primary, ":hover:not(:disabled)": colors.primaryHover },
    borderColor: colors.primary,
    color: colors.primaryForeground,
  },
  ghost: {
    backgroundColor: colors.frame,
    borderColor: { default: hairline, ":hover:not(:disabled)": colors.ring },
    color: colors.foreground,
  },
  fit: { width: "auto", paddingInline: "1.25rem" },
  withMark: { paddingInlineStart: 0 },
  markTile: {
    display: "grid",
    placeItems: "center",
    flexShrink: 0,
    width: "2.625rem",
    height: "2.625rem",
    backgroundColor: colors.primaryForeground,
  },
  buttonLabel: { flex: "1", textAlign: "center" },
  buttonLabelMarked: { marginInlineEnd: "2.625rem" },
  stack: { display: "grid", gap: "0.625rem", marginBlockStart: space.xl },
  submit: { marginBlockStart: space.sm },
  fine: {
    marginBlockStart: "1.125rem",
    fontSize: "0.78125rem",
    lineHeight: 1.5,
    color: muted,
  },
  fineLink: { textDecorationLine: "underline", textUnderlineOffset: "3px" },
  organization: { display: "flex", alignItems: "center", gap: space.lg },
  organizationNote: { fontSize: "0.8125rem", color: muted },
  steps: { display: "flex", gap: space.xs, marginBlockEnd: space.sm },
  step: { flex: "1", height: "3px", backgroundColor: hairline },
  stepDone: { backgroundColor: colors.foreground },
  stepLabel: {
    marginBlockEnd: space.xl,
    fontFamily: typography.mono,
    fontSize: typography.micro,
    letterSpacing: "0.07em",
    textTransform: "uppercase",
    color: muted,
  },
  row: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: space.md,
    marginBlockStart: space.sm,
  },
  regions: { display: "grid", gridTemplateColumns: "repeat(2, minmax(0, 1fr))", gap: space.md },
  region: {
    display: "grid",
    gap: space.xs,
    paddingBlock: space.lg,
    paddingInline: space.lg,
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: { default: hairline, ":hover": colors.ring },
    borderRadius: 0,
    backgroundColor: colors.card,
    color: colors.foreground,
    fontFamily: "inherit",
    textAlign: "start",
    cursor: "pointer",
  },
  regionSelected: {
    borderColor: colors.foreground,
    boxShadow: `inset 0 0 0 1px ${colors.foreground}`,
  },
  regionId: { fontFamily: typography.mono, fontSize: typography.caption, color: muted },
  regionPlace: { fontSize: "0.9375rem" },
  regionLegend: { marginBlockEnd: "0.4375rem", fontSize: "0.84375rem", fontWeight: 500 },
  commandsBox: {
    position: "relative",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: hairline,
    backgroundColor: colors.code,
  },
  commands: {
    margin: 0,
    paddingBlock: space.lg,
    paddingInline: space.lg,
    paddingInlineEnd: "4.5rem",
    fontFamily: typography.mono,
    fontSize: "0.8125rem",
    lineHeight: 1.7,
    overflowX: "auto",
  },
  prompt: { color: muted, userSelect: "none" },
  copyButton: {
    position: "absolute",
    insetBlockStart: 0,
    insetInlineEnd: 0,
    height: "1.75rem",
    paddingInline: space.md,
    borderStyle: "solid",
    borderBlockStartWidth: 0,
    borderInlineEndWidth: 0,
    borderBlockEndWidth: "1px",
    borderInlineStartWidth: "1px",
    borderColor: hairline,
    borderRadius: 0,
    backgroundColor: colors.frame,
    color: { default: muted, ":hover": colors.foreground },
    fontFamily: typography.mono,
    fontSize: typography.micro,
    letterSpacing: "0.07em",
    textTransform: "uppercase",
    cursor: "pointer",
  },
})

/** The device page: the code as separate boxes, then a table of what approving signs in. */
export const deviceStyles = stylex.create({
  prompt: { marginBlockStart: space.xl, fontSize: "0.84375rem", lineHeight: 1.5, color: muted },
  code: {
    display: "grid",
    gridTemplateColumns: "repeat(4, minmax(0, 1fr)) 0.875rem repeat(4, minmax(0, 1fr))",
    gap: space.sm,
    marginBlockStart: "1.125rem",
  },
  box: {
    display: "grid",
    placeItems: "center",
    height: "3.375rem",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: colors.foreground,
    backgroundColor: colors.card,
    color: colors.foreground,
    fontFamily: typography.mono,
    fontSize: "1.5rem",
  },
  separator: { display: "grid", placeItems: "center", color: muted },
  details: {
    margin: 0,
    marginBlockStart: "1.625rem",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: hairline,
  },
  row: {
    display: "flex",
    alignItems: "baseline",
    justifyContent: "space-between",
    gap: space.lg,
    paddingBlock: "0.6875rem",
    paddingInline: "0.875rem",
    borderBlockStartWidth: { default: "1px", ":first-child": 0 },
    borderBlockStartStyle: "solid",
    borderBlockStartColor: hairline,
    fontSize: "0.84375rem",
  },
  term: { color: muted },
  detail: {
    margin: 0,
    fontFamily: typography.mono,
    fontSize: "0.78125rem",
    textAlign: "end",
    overflowWrap: "anywhere",
  },
  email: { display: "block", color: muted },
  actions: {
    display: "grid",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    gap: "0.625rem",
    marginBlockStart: space.xl,
  },
})
